/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CourseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "course";
};

export type Enrollment = {
  _id: string;
  _type: "enrollment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  course?: CourseReference;
  buyer?: EnrollmentBuyer;
  amount?: number;
  currency?: string;
  provider?: "modo";
  providerPaymentId?: string;
  status?: "pending" | "paid" | "failed" | "expired" | "underpaid" | "overpaid";
  classroomAccess?: "pending" | "granted";
  notes?: string;
  modoQr?: string;
  modoDeeplink?: string;
  modoExpiresAt?: string;
};

export type EnrollmentBuyer = {
  _type: "enrollmentBuyer";
  name?: string;
  email?: string;
  dni?: string;
  phone?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
  quota?: number;
  active?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type NetworkPartner = {
  _id: string;
  _type: "networkPartner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoUrl?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
  published?: boolean;
};

export type FocusArea = {
  _id: string;
  _type: "focusArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  icon?: "energy" | "industry40" | "biotech";
  description?: string;
};

export type LandingSettings = {
  _id: string;
  _type: "landingSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroImageUrl?: string;
  aboutTitle?: string;
  aboutBody?: string;
  aboutValues?: Array<
    {
      _key: string;
    } & AboutValue
  >;
  joinTitle?: string;
  joinSubtitle?: string;
  joinBenefits?: Array<string>;
  joinEligibility?: Array<
    {
      _key: string;
    } & EligibilityItem
  >;
  joinCtaText?: string;
  joinCtaLabel?: string;
  contactTitle?: string;
  contactSubtitle?: string;
  formspreeEndpoint?: string;
  footerText?: string;
  socialTwitter?: string;
  socialInstagram?: string;
  socialLinkedin?: string;
  contactEmail?: string;
  statuteUrl?: string;
};

export type EligibilityItem = {
  _type: "eligibilityItem";
  title?: string;
  description?: string;
};

export type AboutValue = {
  _type: "aboutValue";
  icon?: "collaboration" | "debate" | "development" | "knowledge";
  title?: string;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CourseReference
  | Enrollment
  | EnrollmentBuyer
  | SanityImageAssetReference
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | NetworkPartner
  | Project
  | FocusArea
  | LandingSettings
  | EligibilityItem
  | AboutValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
